samples: "/home/d.ence/applications/snakemake_pipelines/pipelines_for_hipergator/ptaeda.induced_terpene_DE/old_induced_terpene_DE/samples.tsv"

units: "/home/d.ence/applications/snakemake_pipelines/pipelines_for_hipergator/ptaeda.induced_terpene_DE/old_induced_terpene_DE/units.tsv"

ref:
        index: "/home/d.ence/d.ence_peter_share/pinus_taeda_L/miami_ohio_ESTs_ptaeda_rbh/t3352.cdna.v1.contig.kallisto"

pca:
        labels:
        - condition 

diffexp:
        contrasts:
                day2-stem-vs-scrappings:
                        - 2MJScrappings
                        - 2MJStem
